name: lisk-core
summary: Lisk blockchain application platform
description: |
  Run lisk-core
adopt-info: lisk-core
architectures: [amd64]

grade: stable
confinement: strict
base: core22

parts:
  lisk-core:
    build-packages:
      - git
      - curl
      - jq
    plugin: nil
    build-environment:
      - NODE_VERSION: 18.19.1
    source: .
    override-build: |
      export PRV=$(pwd)
      export NODE_ARCH=$SNAP_ARCH
      if [[ $NODE_ARCH == "amd64" ]] ; then
          export NODE_ARCH="x64"
      fi
      cd /opt
      curl -o node.tar.gz https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-$NODE_ARCH.tar.gz
      tar -zxf node.tar.gz
      mv node-v$NODE_VERSION-linux-$NODE_ARCH node
      export PATH="/opt/node/bin:$PATH"
      cd "$PRV"
      snapcraftctl set-version "$(jq -r .version < package.json)"
      cd ..
      git clone https://github.com/LiskHQ/dev-cli || true
      cd dev-cli
      npm install --global yarn
      npm install --global typescript
      yarn
      npm run build
      cd ../build
      npm ci
      npm run build
      ../dev-cli/bin/run pack --targets=linux-x64
      cd dist
      find . -name \*linux\*.tar.gz -exec cp {} /root/parts/lisk-core/install \;
      cd ../../install
      tar -zvxf *.tar.gz
      rm *.tar.gz
      mkdir bin
      cp /opt/node/bin/* bin
    stage:
      - lisk-core/*
      - bin/*

apps:
  lisk-core:
    command: lisk-core/bin/lisk-core
    plugs:
      - network
      - network-bind
      - home
