# Base file, do not modifiy.
# Make changes in docker-compose.override.yml instead.
# See https://docs.docker.com/compose/extends/#example-use-case
version: '3'
services:
  lisk:
    image: lisk/core:${ENV_LISK_VERSION}
    volumes:
      - lisk-data:/home/lisk/.lisk
    ports:
      - ${ENV_LISK_HTTP_API_PLUGIN_PORT}:${ENV_LISK_HTTP_API_PLUGIN_PORT}
      - ${ENV_LISK_PORT}:${ENV_LISK_PORT}
    networks:
      - lisk
    restart: unless-stopped
    command: ['--network', '${ENV_LISK_NETWORK}']
    environment:
      - LISK_FILE_LOG_LEVEL=none
      - LISK_CONSOLE_LOG_LEVEL=info

networks:
  lisk:

volumes:
  lisk-data:
