= Core CLI
Muhammad Talha <muhammad.talha@lightcurve.io>
:description: All available CLI commands and topics for Lisk Core including the config file structure are covered here.
:toc: preamble
:page-no-next: true
:url_sdk_references_config: master@lisk-sdk::references/config.adoc

// External URLs
:url_read_eval_print_loop: https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop


The *Core CLI* is a command-line interface that is available for every lisk-core node.

A complete CLI reference of a mainchain node is summarized on this page.

[[clo]]
== Commands

=== help
Displays a summary of all available CLI commands of Lisk Core.

[source,bash]
----
Lisk blockchain application platform

VERSION
  lisk-core/4.0.0-alpha.18 darwin-arm64 node-v16.18.0

USAGE
  $ lisk-core [COMMAND]

TOPICS
  block          Commands relating to Lisk Core blocks.
  blockchain     Commands relating to Lisk Core blockchain data.
  config         Commands relating to Lisk Core node configuration.
  endpoint       Invokes the provided endpoint.
  generator      Disable block generation for given validator address.
  genesis-block  Creates genesis block file.
  keys           Return keys corresponding to the given passphrase.
  node           Commands relating to Lisk Core node.
  passphrase     Commands relating to Lisk Core passphrases.
  sdk            Commands relating to Lisk SDK development.
  transaction    Commands relating to Lisk Core transactions.

COMMANDS
  autocomplete  display autocomplete installation instructions
  console       Lisk interactive REPL session to run commands.
  hash-onion    Create hash onions to be used by the forger.
  help          Display help for lisk-core.
  start         Start Blockchain Node.
  version
----


=== autocomplete
Displays autocomplete installation instructions

[source,bash]
----
USAGE
  $ lisk-core autocomplete [SHELL] [-r]

ARGUMENTS
  SHELL  shell type

FLAGS
  -r, --refresh-cache  Refresh cache (ignores displaying instructions)

DESCRIPTION
  display autocomplete installation instructions

EXAMPLES
  $ lisk-core autocomplete

  $ lisk-core autocomplete bash

  $ lisk-core autocomplete zsh

  $ lisk-core autocomplete --refresh-cache
----

.Example
[%collapsible]
====
[source,bash]
----
$ lisk-core autocomplete
Building the autocomplete cache... done

Setup Instructions for LISK-CORE CLI Autocomplete ---

1) Add the autocomplete env var to your zsh profile and source it
$ printf "eval $(lisk-core autocomplete:script zsh)" >> ~/.zshrc; source ~/.zshrc

NOTE: After sourcing, you can run `$ compaudit -D` to ensure no permissions conflicts are present

2) Test it out, e.g.:
$ lisk-core <TAB>                 # Command completion
$ lisk-core command --<TAB>       # Flag completion

Enjoy!
----
====

=== console
Provides an interactive Javascript {url_read_eval_print_loop}[REPL] session to run LISK commands.

[source,bash]
----
USAGE
  $ lisk-core console [--api-ipc <value>] [--api-ws <value>]

FLAGS
  --api-ipc=<value>  Enable api-client with IPC communication.
  --api-ws=<value>   Enable api-client with Websocket communication.

DESCRIPTION
  Lisk interactive REPL session to run commands.

EXAMPLES
  console

  console --api-ws=ws://localhost:8080

  console --api-ipc=/path/to/server
----

.Example
[%collapsible]
====
[source,bash]
----
$ lisk-core console
Entering Lisk REPL: type `Ctrl+C` or `.exit` to exit
lisk-core >
----
====

=== hash-onion
Creates hash onions to be used by a generator.

[source,bash]
----
USAGE
  $ lisk-core hash-onion [-o <value>] [-c <value>] [-d <value>] [--pretty]

FLAGS
  -c, --count=<value>     [default: 1000000] Total number of hashes to produce
  -d, --distance=<value>  [default: 1000] Distance between each hashes
  -o, --output=<value>    Output file path
  --pretty                Prints JSON in pretty format rather than condensed.

DESCRIPTION
  Create hash onions to be used by the generator.

EXAMPLES
  hash-onion --count=1000000 --distance=2000 --pretty

  hash-onion --count=1000000 --distance=2000 --output ~/my_onion.json
----

.Example
[%collapsible]
====
[source,bash]
----
$ lisk-core hash-onion --count=10 --distance=2 --pretty 
{
  "count": 10,
  "distance": 2,
  "hashes": [
    "e27512a5720052cd61308bef373e9312",
    "3cef453ee632c86651e54ce79614c05e",
    "7ceaefaa0c13111ca93e811a78b26c4e",
    "625b905e51992a1b5a018bca8e37cf4a",
    "6652faaab3427351a8a6c4ac26a19968",
    "eafe02868d94dcedbcf8630776311454"
  ]
}
----
====

=== start
Starts the blockchain node.

[source,bash]
----
USAGE
  $ lisk-core start [-d <value>] [-n <value>] [-c <value>] [--overwrite-config] [-p <value>] [--api-ipc] [--api-ws] [--api-http] [--api-port <value>]
    [--api-host <value>] [-l trace|debug|info|warn|error|fatal] [--seed-peers <value>] [--enable-forger-plugin] [--enable-monitor-plugin] [--monitor-plugin-port <value>]
    [--monitor-plugin-whitelist <value>] [--enable-report-misbehavior-plugin] [--enable-faucet-plugin] [--faucet-plugin-port <value>] [--enable-dashboard-plugin]
    [--dashboard-plugin-port <value>] [--enable-chain-connector-plugin]

FLAGS
  -c, --config=<value>                File path to a custom config. Environment variable "LISK_CONFIG_FILE" can also be used.
  -d, --data-path=<value>             Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
  -l, --log=<option>                  Log level. Environment variable "LISK_LOG_LEVEL" can also be used.
                                      <options: trace|debug|info|warn|error|fatal>
  -n, --network=<value>               [default: default] Default network config to use. Environment variable "LISK_NETWORK" can also be used.
  -p, --port=<value>                  Open port for the peer to peer incoming connections. Environment variable "LISK_PORT" can also be used.
  --api-host=<value>                  Host to be used for api-client. Environment variable "LISK_API_HOST" can also be used.
  --api-http                          Enable HTTP communication for api-client. Environment variable "LISK_API_HTTP" can also be used.
  --api-ipc                           Enable IPC communication. This will load plugins as a child process and communicate over IPC. Environment variable "LISK_API_IPC"
                                      can also be used.
  --api-port=<value>                  Port to be used for api-client. Environment variable "LISK_API_PORT" can also be used.
  --api-ws                            Enable websocket communication for api-client. Environment variable "LISK_API_WS" can also be used.
  --dashboard-plugin-port=<value>     Port to be used for Dashboard Plugin. Environment variable "LISK_DASHBOARD_PLUGIN_PORT" can also be used.
  --enable-chain-connector-plugin     Enable Chain Connector Plugin. Environment variable "LISK_ENABLE_CHAIN_CONNECTOR_PLUGIN" can also be used.
  --enable-dashboard-plugin           Enable Dashboard Plugin. Environment variable "LISK_ENABLE_DASHBOARD_PLUGIN" can also be used.
  --enable-faucet-plugin              Enable Faucet Plugin. Environment variable "LISK_ENABLE_FAUCET_PLUGIN" can also be used.
  --enable-forger-plugin              Enable Forger Plugin. Environment variable "LISK_ENABLE_FORGER_PLUGIN" can also be used.
  --enable-monitor-plugin             Enable Monitor Plugin. Environment variable "LISK_ENABLE_MONITOR_PLUGIN" can also be used.
  --enable-report-misbehavior-plugin  Enable ReportMisbehavior Plugin. Environment variable "LISK_ENABLE_REPORT_MISBEHAVIOR_PLUGIN" can also be used.
  --faucet-plugin-port=<value>        Port to be used for Faucet Plugin. Environment variable "LISK_FAUCET_PLUGIN_PORT" can also be used.
  --monitor-plugin-port=<value>       Port to be used for Monitor Plugin. Environment variable "LISK_MONITOR_PLUGIN_PORT" can also be used.
  --monitor-plugin-whitelist=<value>  List of IPs in comma separated value to allow the connection. Environment variable "LISK_MONITOR_PLUGIN_WHITELIST" can also be used.
  --overwrite-config                  Overwrite network configs if they exist already
  --seed-peers=<value>                Seed peers to initially connect to in format of comma separated "ip:port". IP can be DNS name or IPV4 format. Environment variable
                                      "LISK_SEED_PEERS" can also be used.

DESCRIPTION
  Start Blockchain Node.

EXAMPLES
  start

  start --network devnet --data-path /path/to/data-dir --log debug

  start --network devnet --api-ws

  start --network devnet --api-ws --api-port 8888

  start --network devnet --port 9000

  start --network devnet --port 9002 --seed-peers 127.0.0.1:9001,127.0.0.1:9000

  start --network testnet --overwrite-config

  start --network testnet --config ~/my_custom_config.json
----

.Example
[%collapsible]
====
[source,bash]
----
$ lisk-core start --network devnet --api-ws
----
====

== Topics

=== block
Commands relating to Lisk Core blocks.

[source,bash]
----
USAGE
  $ lisk-core block COMMAND

COMMANDS
  block get  Get block information for a given id or height.
----

==== block:get
Gets block information for a given id or height.

[source,bash]
----
USAGE
  $ lisk-core block get [INPUT] [-d <value>] [--pretty]

ARGUMENTS
  INPUT  Height in number or block id in hex format.

FLAGS
  -d, --data-path=<value>  Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
  --pretty                 Prints JSON in pretty format rather than condensed.

DESCRIPTION
  Get block information for a given id or height.

EXAMPLES
  block:get e082e79d01016632c451c9df9276e486cb7f460dc793ff5b10d8f71eecec28b4

  block:get 2
----

.Example
[%collapsible]
====
[source,bash]
----
$ lisk-core block:get 2 --pretty
{
  "header": {
    "version": 2,
    "timestamp": 1680868980,
    "height": 2,
    "previousBlockID": "9e442947fda74955dea2e6a490b1158a78655bd5fb6875cd945bdc02841523fd",
    "stateRoot": "2211e781083d5def0da750cf96f75abd3b27d68e944ba01728ddfb4fb18fa5d2",
    "assetRoot": "8fb5ed936653eba7fb8e05fa7ad87a75e10347ca544574326dd11d159bcd015d",
    "eventRoot": "15caa254f64d161c61daede6f2fec75451381a1268b83997ebe86887c81ca2c8",
    "transactionRoot": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "validatorsHash": "8438b6d8c70e18c79a9215f53b6c4677e2f4bab793479a35c03d8f514f3389b3",
    "aggregateCommit": {
      "height": 0,
      "aggregationBits": "",
      "certificateSignature": ""
    },
    "generatorAddress": "lsket9bd2coqrbbojp2fnj744atmuk6ys6yumu384",
    "maxHeightPrevoted": 0,
    "maxHeightGenerated": 0,
    "impliesMaxPrevotes": true,
    "signature": "dd76712757a43d1324e2f3e40adea505f8a48a30760301d379321ff483fb2ff136f83877b6a4c12bfd23dd374461be1bc8212ccb07ba3fc4dbbb6f58babc6004",
    "id": "f74a3057308ef04fbececeda16b2cb65226f076bb8d2bf026e3982b860758b6d"
  },
  "transactions": [],
  "assets": [
    {
      "module": "random",
      "data": {
        "seedReveal": "efb5d9ada0e8e85cb4f97efa61a1e5ee"
      }
    }
  ]
}
----
====


=== blockchain
Commands relating to Lisk Core blockchain data.

[source,bash]
----
USAGE
  $ lisk-core blockchain COMMAND

COMMANDS
  blockchain download  Download snapshot from <URL>.
  blockchain export    Export to <FILE>.
  blockchain hash      Generate SHA256 hash from <PATH>.
  blockchain import    Import from <FILE>.
  blockchain reset     Reset the blockchain data.
----

==== blockchain:download
Download snapshot from the given <URL>.

[source,bash]
----
USAGE
  $ lisk-core blockchain download [-n <value>] [-o <value>] [-u <value>]

FLAGS
  -n, --network=<value>  [default: mainnet] Default network config to use. Environment variable "LISK_NETWORK" can also be used.
  -o, --output=<value>   Directory path to specify where snapshot is downloaded. By default outputs the files to current working directory.
  -u, --url=<value>      The url to the snapshot.

DESCRIPTION
  Download snapshot from <URL>.

EXAMPLES
  download

  download --network betanet

  download --url https://snapshots.lisk.com/mainnet/blockchain.db.tar.gz --output ./downloads

----

.Example 
[%collapsible]
====
[source,bash]
----
$ lisk-core blockchain:download
Downloading snapshot from https://snapshots.lisk.com/mainnet/blockchain.db.tar.gz to /Users/XYZ
Downloaded to path: /Users/XYZ
----
====


==== blockchain:export
Exports the blockchain's data to a file.

[source,bash]
----
USAGE
  $ lisk-core blockchain export [-d <value>] [-o <value>]

FLAGS
  -d, --data-path=<value>  Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
  -o, --output=<value>     The output directory. Default will set to current working directory.

DESCRIPTION
  Export to <FILE>.

EXAMPLES
  blockchain:export

  blockchain:export --data-path ./data --output ./my/path/
----

.Example 
[%collapsible]
====
[source,bash]
----
$ lisk-core blockchain:export
Exporting blockchain:
   /Users/XYZ/.lisk/lisk-core/data
Export completed:
   /Users/XYZ/blockchain.tar.gz
----
====

==== blockchain:hash
Generates SHA256 hash from the blockchain\'s data.

[source,bash]
----
USAGE
  $ lisk-core blockchain hash [-d <value>]

FLAGS
  -d, --data-path=<value>  Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.

DESCRIPTION
  Generate SHA256 hash from <PATH>.

EXAMPLES
  blockchain:hash

  blockchain:hash --data-path ./data
----

.Example 
[%collapsible]
====
[source,bash]
----
$ lisk-core blockchain:hash --data-path /Users/xyz/blockchain.db
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
----
====

==== blockchain:import
Imports the blockchain's data from a file.

[source,bash]
----
USAGE
  $ lisk-core blockchain import [FILEPATH] [-d <value>] [-f]

ARGUMENTS
  FILEPATH  Path to the gzipped blockchain data.

FLAGS
  -d, --data-path=<value>  Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
  -f, --force              Delete and overwrite existing blockchain data

DESCRIPTION
  Import from <FILE>.

EXAMPLES
  blockchain:import ./path/to/blockchain.tar.gz

  blockchain:import ./path/to/blockchain.tar.gz --data-path ./lisk/

  blockchain:import ./path/to/blockchain.tar.gz --data-path ./lisk/ --force
----

.Example 
[%collapsible]
====
[source,bash]
----
$ lisk-core blockchain:import /Users/XYZ/blockchain.tar.gz --force
Importing blockchain from /Users/XYZ/blockchain.tar.gz
Import completed.
   /Users/XYZ/.lisk/lisk-core
----
====


==== blockchain:reset
Resets the blockchain's data.

[source,bash]
----
USAGE
  $ lisk-core blockchain reset [-d <value>] [-y]

FLAGS
  -d, --data-path=<value>  Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
  -y, --yes                Skip confirmation prompt.

DESCRIPTION
  Reset the blockchain data.

EXAMPLES
  blockchain:reset

  blockchain:reset --data-path ./lisk

  blockchain:reset --yes
----

.Example 
[%collapsible]
====
[source,bash]
----
$ lisk-core blockchain:reset
? Are you sure you want to reset the db? yes
Blockchain data has been reset.
----
====

=== config
Commands relating to the configuration of the blockchain client.

[source,bash]
----
USAGE
  $ lisk-core config COMMAND

COMMANDS
  config create  Creates network configuration file.
  config show    Show application config.
----


==== config:create
Creates a configuration file for the blockchain application.

[source,bash]
----
USAGE
  $ lisk-core config create -i <value> [-o <value>] [-l <value>]

FLAGS
  -i, --chain-id=<value>  (required) ChainID in hex format. For example, Lisk mainnet mainchain is 00000000
  -l, --label=<value>     [default: beta-sdk-app] App Label
  -o, --output=<value>    [default: /home/lisk/workspace/lisk-core-publish_development/lisk-core] Directory where the config file is saved

DESCRIPTION
  Creates network configuration file.

EXAMPLES
  config:create --output mydir

  config:create --output mydir --label beta-sdk-app

  config:create --output mydir --label beta-sdk-app --community-identifier sdk
----

.Example 
[%collapsible]
====
[source,bash]
----
$ lisk-core config:create --output /Users/XYZ --chain-id 04000000
----
====


==== config:show
Shows the application's config.

[source,bash]
----
USAGE
  $ lisk-core config show [-d <value>] [-c <value>] [--pretty]

FLAGS
  -c, --config=<value>     File path to a custom config. Environment variable "LISK_CONFIG_FILE" can also be used.
  -d, --data-path=<value>  Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
  --pretty                 Prints JSON in pretty format rather than condensed.

DESCRIPTION
  Show application config.

EXAMPLES
  config:show

  config:show --pretty

  config:show --config ./custom-config.json --data-path ./data
----

.Example 
[%collapsible]
====
[source,bash]
----
$ lisk-core config:show --pretty
{
  "system": {
    "dataPath": "/Users/XYZ/.lisk/lisk-core",
    "logLevel": "info",
    "keepEventsForHeights": -1
  },
  "rpc": {
    "modes": [
      "ipc",
      "ws",
      "http"
    ],
    "port": 7887,
    "host": "0.0.0.0"
  },
  "genesis": {
    "block": {
      "fromFile": "./config/genesis_block.blob"
    },
    "blockTime": 10,
    "bftBatchSize": 103,
    "chainID": "04000000",
    "maxTransactionsSize": 15360
  },
  "generator": {
    "keys": {
      "fromFile": "./config/dev-validators.json"
    }
  },
  "network": {
    "version": "1.0",
    "seedPeers": [],
    "port": 7667
  },
  "transactionPool": {
    "maxTransactions": 4096,
    "maxTransactionsPerAccount": 64,
    "transactionExpiryTime": 10800000,
    "minEntranceFeePriority": "0",
    "minReplacementFeeDifference": "10"
  },
  "modules": {
    "dynamicReward": {
      "tokenID": "0400000000000000",
      "offset": 360,
      "distance": 1000,
      "brackets": [
        "500000000",
        "400000000",
        "300000000",
        "200000000",
        "100000000"
      ]
    },
    "fee": {
      "feeTokenID": "0400000000000000"
    },
    "pos": {
      "useInvalidBLSKey": false
    },
    "token": {
      "feeTokenID": "0400000000000000"
    }
  },
  "plugins": {
  }
}
----
====

=== endpoint
Commands relating to invoking and listing the endpoints.

[source,bash]
----
USAGE
  $ lisk-core endpoint COMMAND

COMMANDS
  endpoint invoke  Invokes the provided endpoint.
  endpoint list    Lists registered endpoints.
----

==== endpoint:invoke
Invokes the provided endpoint.

[source,bash]
----
USAGE
  $ lisk-core endpoint invoke [ENDPOINT] [PARAMS] [-d <value>] [--pretty] [-f <value>]

ARGUMENTS
  ENDPOINT  Endpoint to invoke
  PARAMS    Endpoint parameters (Optional)

FLAGS
  -d, --data-path=<value>  Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
  -f, --file=<value>       Input file.
  --pretty                 Prints JSON in pretty format rather than condensed.

DESCRIPTION
  Invokes the provided endpoint.

EXAMPLES
  endpoint:invoke {endpoint} {parameters}

  endpoint:invoke --data-path --file

  endpoint:invoke generator_getAllKeys

  endpoint:invoke consensus_getBFTParameters '{"height": 2}' -d ~/.lisk/pos-mainchain --pretty

  endpoint:invoke consensus_getBFTParameters -f ./input.json
----

.Example 
[%collapsible]
====
[source,bash]
----
$ lisk-core endpoint:invoke system_getNodeInfo --pretty
{
  "version": "4.0.0-alpha.18",
  "networkVersion": "1.0",
  "chainID": "04000000",
  "lastBlockID": "dd207c37a76c453e4b718f2bf238b84186f6e673679915b197ce1fdf94d3c180",
  "height": 49,
  "finalizedHeight": 0,
  "syncing": false,
  "unconfirmedTransactions": 0,
  "genesisHeight": 0,
  "genesis": {
    "block": {
      "fromFile": "./config/genesis_block.blob"
    },
    "blockTime": 10,
    "bftBatchSize": 103,
    "maxTransactionsSize": 15360,
    "chainID": "04000000"
  },
  "network": {
    "version": "1.0",
    "port": 7667,
    "seedPeers": []
  }
}
----
====

==== endpoint:list
Returns the list of all the module endpoints

[source,bash]
----
USAGE
  $ lisk-core endpoint list [ENDPOINT] [-d <value>] [--pretty] [-m <value>] [-i]

ARGUMENTS
  ENDPOINT  Endpoint name (Optional)

FLAGS
  -d, --data-path=<value>  Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
  -i, --info               Prints additional info; Request and Response objects.
  -m, --module=<value>     Parent module.
  --pretty                 Prints JSON in pretty format rather than condensed.

DESCRIPTION
  Lists registered endpoints.

EXAMPLES
  endpoint:list

  endpoint:list {endpoint} -m {module}

  endpoint:list {endpoint} -m {module} -i

  endpoint:list -m validator

  endopint:list getBalance

  endpoint:list get -m token

  endpoint:list getBalances -m token -i --pretty

  endpoint:list getBalances -m token -d ~/.lisk/pos-mainchain
----

.Example 
[%collapsible]
====
[source,bash]
----
$ lisk-core endpoint:list --pretty
[
  "auth_getAuthAccount",
  "auth_isValidNonce",
  "auth_isValidSignature",
  "auth_getMultiSigRegMsgSchema",
  "auth_sortMultisignatureGroup",
  "auth_getMultiSigRegMsgTag",
  "dynamicReward_getDefaultRewardAtHeight",
  "dynamicReward_getAnnualInflation",
  "dynamicReward_getRewardTokenID",
  "fee_getMinFeePerByte",
  "fee_getFeeTokenID",
  "interoperability_getChainAccount",
  "interoperability_getAllChainAccounts",
  "interoperability_getChannel",
  "interoperability_getOwnChainAccount",
  "interoperability_getTerminatedStateAccount",
  "interoperability_getTerminatedOutboxAccount",
  "interoperability_getRegistrationFee",
  "interoperability_getMinimumMessageFee",
  "interoperability_getChainValidators",
  "interoperability_isChainIDAvailable",
  "interoperability_isChainNameAvailable",
  "legacy_getLegacyAccount",
  "pos_getAllValidators",
  "pos_getValidator",
  "pos_getStaker",
  "pos_getConstants",
  "pos_getPoSTokenID",
  "pos_getClaimableRewards",
  "pos_getLockedReward",
  "pos_getLockedStakedAmount",
  "pos_getValidatorsByStake",
  "pos_getPendingUnlocks",
  "pos_getRegistrationFee",
  "random_isSeedRevealValid",
  "random_setHashOnion",
  "random_getHashOnionSeeds",
  "random_hasHashOnion",
  "random_getHashOnionUsage",
  "token_getBalance",
  "token_getBalances",
  "token_getTotalSupply",
  "token_getSupportedTokens",
  "token_isSupported",
  "token_getEscrowedAmounts",
  "token_getInitializationFees",
  "token_hasUserAccount",
  "token_hasEscrowAccount",
  "validators_validateBLSKey",
  "validators_getValidator"
]
----
====

=== generator
Commands relating to the block generation and generator-info of a blockchain.
[source,bash]
----
USAGE
  $ lisk-core generator COMMAND

COMMANDS
  generator disable  Disable block generation for given validator address.
  generator enable   Enable block generation for given validator address.
  generator export   Export to <FILE>.
  generator import   Import from <FILE>.
  generator status   Get forging information for the locally running node.
----

==== generator:disable
Disables block generation for a given generator's address.

[source,bash]
----
USAGE
  $ lisk-core generator disable [ADDRESS] [-d <value>] [--pretty] [-w <value>]

ARGUMENTS
  ADDRESS  Address of an account in a lisk32 format.

FLAGS
  -d, --data-path=<value>  Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
  -w, --password=<value>   Specifies a source for your secret password. Command will prompt you for input if this option is not set.
                           	Examples:
                           	- --password=pass:password123 (should only be used where security is not important)
  --pretty                 Prints JSON in pretty format rather than condensed.

DESCRIPTION
  Disable block generation for given validator address.

EXAMPLES
  generator:disable lskycz7hvr8yfu74bcwxy2n4mopfmjancgdvxq8xz

  generator:disable lskycz7hvr8yfu74bcwxy2n4mopfmjancgdvxq8xz --data-path ./data

  generator:disable lskycz7hvr8yfu74bcwxy2n4mopfmjancgdvxq8xz --data-path ./data --password your_password
----

.Example
[%collapsible]
====
[source,bash]
----
$ lisk-core generator:disable lskqaxxmj78frvgpjgwvf4yqjjkcrr9yhn2sxxwm3
? Enter password to decrypt the encrypted passphrase:  ********

Disabled block generation for lskqaxxmj78frvgpjgwvf4yqjjkcrr9yhn2sxxwm3
----
====

==== generator:enable
Enables block generation for a given generator\'s address.

[source,bash]
----
USAGE
  $ lisk-core generator enable [ADDRESS] [-d <value>] [--pretty] [-w <value>] [--height <value>] [--max-height-generated <value>] [--max-height-prevoted <value>]
    [--use-status-value]

ARGUMENTS
  ADDRESS  Address of an account in a lisk32 format.

FLAGS
  -d, --data-path=<value>         Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
  -w, --password=<value>          Specifies a source for your secret password. Command will prompt you for input if this option is not set.
                                  	Examples:
                                  	- --password=pass:password123 (should only be used where security is not important)
  --height=<value>                Last generated block height.
  --max-height-generated=<value>  Validator's largest previously generated height.
  --max-height-prevoted=<value>   Validator's largest prevoted height for a block.
  --pretty                        Prints JSON in pretty format rather than condensed.
  --use-status-value              Use status value from the connected node

DESCRIPTION
  Enable block generation for given validator address.

EXAMPLES
  generator:enable lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu --use-status-value

  generator:enable lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu --height=100 --max-height-generated=30 --max-height-prevoted=10

  generator:enable lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu --height=100 --max-height-generated=30 --max-height-prevoted=10 --data-path ./data

  generator:enable lsk24cd35u4jdq8szo3pnsqe5dsxwrnazyqqqg5eu --height=100 --max-height-generated=30 --max-height-prevoted=10 --data-path ./data --password your_password
----

.Example
[%collapsible]
====
[source,bash]
----
$ lisk-core generator:enable lskqaxxmj78frvgpjgwvf4yqjjkcrr9yhn2sxxwm3 --use-status-value

 Current block generation status for validator account lskqaxxmj78frvgpjgwvf4yqjjkcrr9yhn2sxxwm3 is:
{"height":14814092,"maxHeightPrevoted":14814017,"maxHeightGenerated":14814025}
? Do you want to use the above values to enable block generation? yes
? Enter password to decrypt the encrypted passphrase:  ********

Updated block generation status:
{"address":"lskqaxxmj78frvgpjgwvf4yqjjkcrr9yhn2sxxwm3","enabled":true}
----
====


==== generator:export
Exports generator's data to a file.

[source,bash]
----
USAGE
  $ lisk-core generator export [-d <value>] [--pretty] [-o <value>]

FLAGS
  -d, --data-path=<value>  Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
  -o, --output=<value>     The output directory. Default will set to current working directory.
  --pretty                 Prints JSON in pretty format rather than condensed.

DESCRIPTION
  Export to <FILE>.

EXAMPLES
  generator:export --output /mypath/genInfo.json

  generator:export --output /mypath/genInfo.json --data-path ./data
----

.Example 
[%collapsible]
====
[source,bash]
----
$ lisk-core generator export --output /Users/XYZ/genInfo.json
----
====

==== generator:import
Imports generator's data from a file.

[source,bash]
----
USAGE
  $ lisk-core generator import -f <value> [-d <value>] [--pretty]

FLAGS
  -d, --data-path=<value>  Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
  -f, --file-path=<value>  (required) Path of the file to import from
  --pretty                 Prints JSON in pretty format rather than condensed.

DESCRIPTION
  Import from <FILE>.

EXAMPLES
  generator:import --file-path ./my/path/genInfo.json

  generator:import --file-path ./my/path/genInfo.json --data-path ./data
----

.Example 
[%collapsible]
====
[source,bash]
----
$./bin/run generator:import --file-path /Users/XYZ/genInfo.json
----
====

==== generator:status
Gets block generation information for the locally running node.

[source,bash]
----
USAGE
  $ lisk-core generator status [-d <value>] [--pretty]

FLAGS
  -d, --data-path=<value>  Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
  --pretty                 Prints JSON in pretty format rather than condensed.

DESCRIPTION
  Get forging information for the locally running node.

EXAMPLES
  generator:status

  generator:status --data-path ./sample --pretty
----

.Example 
[%collapsible]
====
[source,bash]
----
$ lisk-core generator:status --pretty
{
  "info": {
    "status":
    [{
        "address": "lskzpvesvp7p9odszcp3s4dffnj4ozqz7b79tonqp",
        "height": 574,
        "maxHeightPrevoted": 487,
        "maxHeightGenerated": 459,
        "enabled": true
      }
  ]}
}
----
====


=== genesis-block
Commands relating to the genesis-block.

[source,bash]
----
USAGE
  $ lisk-core genesis-block COMMAND

COMMANDS
  genesis-block create    Creates genesis block file.
  genesis-block download  Download genesis block.
----

==== genesis-block:create
Creates a genesis block file and the corresponding generator\'s configuration data and accounts information.

[source,bash]
----
USAGE
  $ lisk-core genesis-block create -f <value> [-n <value>] [-c <value>] [-o <value>]

FLAGS
  -c, --config=<value>       File path to a custom config. Environment variable "LISK_CONFIG_FILE" can also be used.
  -f, --assets-file=<value>  (required) Path to file which contains genesis block asset in JSON format
  -n, --network=<value>      [default: default] Default network config to use. Environment variable "LISK_NETWORK" can also be used.
  -o, --output=<value>       [default: config] Output folder path of the generated genesis block

DESCRIPTION
  Creates genesis block file.

EXAMPLES
  genesis-block:create --output mydir

  genesis-block:create --output mydir --assets-file ./assets.json
----

.Example 
[%collapsible]
====
[source,bash]
----
$ lisk-core genesis-block:create --assets-file genesis_assets.json --output ./devnet                                                                                  ─╯
2023-04-07T16:47:08.874Z INFO XYZ.local application 55996 Registered and initialized fee module
2023-04-07T16:47:08.875Z INFO XYZ.local application 55996 Registered and initialized auth module
2023-04-07T16:47:08.875Z INFO XYZ.local application 55996 Registered auth module has command registerMultisignature
2023-04-07T16:47:08.875Z INFO XYZ.local application 55996 Registered and initialized validators module
2023-04-07T16:47:08.876Z INFO XYZ.local application 55996 Registered and initialized token module
2023-04-07T16:47:08.876Z INFO XYZ.local application 55996 Registered token module has command transfer
2023-04-07T16:47:08.876Z INFO XYZ.local application 55996 Registered token module has command transferCrossChain
2023-04-07T16:47:08.878Z INFO XYZ.local application 55996 Registered and initialized dynamicReward module
2023-04-07T16:47:08.878Z INFO XYZ.local application 55996 Registered and initialized random module
2023-04-07T16:47:08.881Z INFO XYZ.local application 55996 Registered and initialized pos module
2023-04-07T16:47:08.881Z INFO XYZ.local application 55996 Registered pos module has command registerValidator
2023-04-07T16:47:08.881Z INFO XYZ.local application 55996 Registered pos module has command reportMisbehavior
2023-04-07T16:47:08.881Z INFO XYZ.local application 55996 Registered pos module has command unlock
2023-04-07T16:47:08.881Z INFO XYZ.local application 55996 Registered pos module has command updateGeneratorKey
2023-04-07T16:47:08.881Z INFO XYZ.local application 55996 Registered pos module has command stake
2023-04-07T16:47:08.881Z INFO XYZ.local application 55996 Registered pos module has command changeCommission
2023-04-07T16:47:08.881Z INFO XYZ.local application 55996 Registered pos module has command claimRewards
2023-04-07T16:47:08.881Z INFO XYZ.local application 55996 Registered and initialized interoperability module
2023-04-07T16:47:08.881Z INFO XYZ.local application 55996 Registered interoperability module has command submitMainchainCrossChainUpdate
2023-04-07T16:47:08.881Z INFO XYZ.local application 55996 Registered interoperability module has command initializeMessageRecovery
2023-04-07T16:47:08.881Z INFO XYZ.local application 55996 Registered interoperability module has command recoverMessage
2023-04-07T16:47:08.881Z INFO XYZ.local application 55996 Registered interoperability module has command registerSidechain
2023-04-07T16:47:08.881Z INFO XYZ.local application 55996 Registered interoperability module has command recoverState
2023-04-07T16:47:08.881Z INFO XYZ.local application 55996 Registered interoperability module has command terminateSidechainForLiveness
2023-04-07T16:47:08.881Z INFO XYZ.local application 55996 Registered and initialized legacy module
2023-04-07T16:47:08.881Z INFO XYZ.local application 55996 Registered legacy module has command reclaimLSK
2023-04-07T16:47:08.881Z INFO XYZ.local application 55996 Registered legacy module has command registerKeys
Genesis block files saved at: /Users/XYZ/.nvm/versions/node/v16.18.0/lib/node_modules/lisk-core/config/devnet/devnet
----
====

=== keys
Return keys corresponding to the given passphrase.

[source,bash]
----
USAGE
  $ lisk-core keys COMMAND

COMMANDS
  keys create   Return keys corresponding to the given passphrase.
  keys encrypt  Encrypt keys from a file and overwrite the file
  keys export   Export to <FILE>.
  keys import   Import from <FILE>.
----



==== keys:create
Return keys corresponding to the given passphrase.

[source,bash]
----
USAGE
  $ lisk-core keys create [-o <value>] [-p <value>] [-n] [-w <value>] [-c <value>] [-f <value>] [-i <value>]

FLAGS
  -c, --count=<value>       [default: 1] Number of keys to create
  -f, --offset=<value>      Offset for the key derivation path
  -i, --chainid=<value>     Chain id
  -n, --no-encrypt          No encrypted message object to be created
  -o, --output=<value>      The output directory. Default will set to current working directory.
  -p, --passphrase=<value>  Specifies a source for your secret passphrase. Command will prompt you for input if this option is not set.
                            	Examples:
                            	- --passphrase='my secret passphrase' (should only be used where security is not important)
  -w, --password=<value>    Specifies a source for your secret password. Command will prompt you for input if this option is not set.
                            	Examples:
                            	- --password=pass:password123 (should only be used where security is not important)

DESCRIPTION
  Return keys corresponding to the given passphrase.

EXAMPLES
  keys:create

  keys:create --passphrase your-passphrase

  keys:create --passphrase your-passphrase --no-encrypt

  keys:create --passphrase your-passphrase --password your-password

  keys:create --passphrase your-passphrase --password your-password --count 2

  keys:create --passphrase your-passphrase --no-encrypt --count 2 --offset 1

  keys:create --passphrase your-passphrase --no-encrypt --count 2 --offset 1 --chainid 1

  keys:create --passphrase your-passphrase --password your-password --count 2 --offset 1 --chainid 1 --output /mypath/keys.json
----

.Example 
[%collapsible]
====
[source,bash]
----
$ lisk-core keys create
? Please enter passphrase:  [hidden]
? Please re-enter passphrase:  [hidden]
Warning: Passphrase contains 24 words instead of expected 12. Passphrase contains 23 whitespaces instead of expected 11.
? Please enter password:  [hidden]
? Please re-enter password:  [hidden]
{
  "keys": [
    {
      "address": "lskguo9kqnea2zsfo3a6qppozsxsg92nuuma3p7ad",
      "keyPath": "m/44'/134'/0'",
      "publicKey": "3972849f2ab66376a68671c10a00e8b8b67d880434cc65b04c6ed886dfa91c2c",
      "privateKey": "e655ee58490c66dee3f6761f3b69fdcb65def01615efcddde09c791d6fc2a5223972849f2ab66376a68671c10a00e8b8b67d880434cc65b04c6ed886dfa91c2c",
      "plain": {
        "generatorKeyPath": "m/25519'/134'/0'/0'",
        "generatorKey": "7da039d08ca35bc7c7e3583f2544754b9fdd8877edb82da02cbe1fde8ab7c113",
        "generatorPrivateKey": "e35c5fb116704d11309ad9a96b36c8bb20acb1c435bfe44cfef6b6aa2111c1b87da039d08ca35bc7c7e3583f2544754b9fdd8877edb82da02cbe1fde8ab7c113",
        "blsKeyPath": "m/12381/134/0/0",
        "blsKey": "82ecd08a07380c29e656527d339ffe1fe306f0f97cd077335afb3c1c1bdb73918a40f15c410bdc4facca9172088c9262",
        "blsProofOfPossession": "9950069539cf1baec7b7629eb45d618fd052fd15da108a6b8e6018a7ec8d4957b777b858f6e194a336a4a51c0d709409045646f9588b2be49f11563c549a711957337b2589370cabb2d795cb44f68c7507ca84a9d3a354df2d82f2d158f9e504",
        "blsPrivateKey": "3a2ca861b00aa00a3c1ae00ed0252cb944a6b9dba37d8882ca4f757aafd6f2fe"
      },
      "encrypted": {
        "ciphertext": "291bbb535b7eb9dbfc300f13b5e031a684392f35a37618d76917073e57ddfe63351f953301a7b7ac986d13c080f5b1fcbae968084a29fae5e621b60f1ec1f600c48a24bd7fe8b25c9dc7f8be68e26fe664d20b36e5da86784413a42b2400f84725bf2180be37b2d1a14d4b02a1ebe977bad08d360fd5e1488b85311e64e7d4b5534653fdf90874a706c34c06b1774e30a4dea544067927cd4ff8e74d08ab39ba2c1855739be6dd85ffd2ce298a012a54fbc129797a8f6cf7",
        "mac": "33b6e7ae77b87ff7eb569fdcfd206e63fd719106635cfd6f09eaba8cdd02df39",
        "kdf": "argon2id",
        "kdfparams": {
          "parallelism": 4,
          "iterations": 1,
          "memorySize": 2024,
          "salt": "7920fdf927717ec27463416fd44e83ac"
        },
        "cipher": "aes-256-gcm",
        "cipherparams": {
          "iv": "fc9c300aacd987b71bc45354",
          "tag": "033470f223f59f40462647055203ff74"
        },
        "version": "1"
      }
    }
  ]
}
----
====


==== keys:encrypt
Encrypt keys from a file and overwrite the file.

[source,bash]
----
USAGE
  $ lisk-core keys encrypt -f <value> [-w <value>]

FLAGS
  -f, --file-path=<value>  (required) Path of the file to encrypt from
  -w, --password=<value>   Specifies a source for your secret password. Command will prompt you for input if this option is not set.
                           	Examples:
                           	- --password=pass:password123 (should only be used where security is not important)

DESCRIPTION
  Encrypt keys from a file and overwrite the file

EXAMPLES
  keys:encrypt --file-path ./my/path/keys.json

  keys:encrypt --file-path ./my/path/keys.json --password mypass
----


.Example 
[%collapsible]
====
[source,bash]
----
$ lisk-core keys:encrypt --file-path ./my/path/keys.json --password mypass
{
  "keys": [
      {
        "address": "lske5sqed53fdcs4m9et28f2k7u9fk6hno9bauday",
        "keyPath": "m/44'/134'/0'",
        "publicKey": "a3f96c50d0446220ef2f98240898515cbba8155730679ca35326d98dcfb680f0",
        "privateKey": "d0b159fe5a7cc3d5f4b39a97621b514bc55b0a0f1aca8adeed2dd1899d93f103a3f96c50d0446220ef2f98240898515cbba8155730679ca35326d98dcfb680f0",
        "plain": {
          "generatorKeyPath": "m/25519'/134'/0'/0'",
          "generatorKey": "b9e54121e5346cc04cc84bcf286d5e40d586ba5d39571daf57bd31bac3861a4a",
          "generatorPrivateKey": "b3c4de7f7932275b7a465045e918337ffd7b7b229cef8eba28f706de8759da95b9e54121e5346cc04cc84bcf286d5e40d586ba5d39571daf57bd31bac3861a4a",
          "blsKeyPath": "m/12381/134/0/0",
          "blsKey": "92f020ce5e37befb86493a82686b0eedddb264350b0873cf1eeaa1fefe39d938f05f272452c1ef5e6ceb4d9b23687e31",
          "blsProofOfPosession": "b92b11d66348e197c62d14af1453620d550c21d59ce572d95a03f0eaa0d0d195efbb2f2fd1577dc1a04ecdb453065d9d168ce7648bc5328e5ea47bb07d3ce6fd75f35ee51064a9903da8b90f7dc8ab4f2549b834cb5911b883097133f66b9ab9",
          "blsPrivateKey": "463dd3413051366ee658c2524dd0bec85f8459bf6d70439685746406604f950d"
      },
      "encrypted": {
          "ciphertext": "d340438fde7b744d7482f01531415ffc0bda70dac36257571bb0dab703771e83152428b4a4dddc77dff1a983f07b0f3cba688fab2e46abe970ae4131c616e6cbf613952786f5749e94531641f07fcdef38a001a44f56f5de69e0976964ea13cbaff0682b5e0eaf9ff01a00f5b2215a3a1d9e3f0d5b78c876b157213367f7f90a468937c0baf9904189c21870c396b43b53422422bd61a3e1c8cb3126e1a5d60545aa06ee789c89dfb9155b560c327a88af5f9b04b4c6d4e9",
          "mac": "d476a90c1fb057a1e4ece0d725f40f67ae36efcc166aede5380115d2a7532833",
          "kdf": "argon2id",
          "kdfparams": {
          "parallelism": 4,
          "iterations": 1,
          "memorySize": 2024,
          "salt": "ecc014a7619b7f179b3fa32d2fed5d6c"
          },
          "cipher": "aes-256-gcm",
          "cipherparams": {
          "iv": "328cf25fdda6988ed9f1101e",
          "tag": "1862fde73a2a7b71979773bf620872ef"
          },
          "version": "1"
        }
    }
  ]
}
----
====



==== keys:export
Export keys to a file.

[source,bash]
----
USAGE
  $ lisk-core keys export -o <value> [-d <value>] [--pretty]

FLAGS
  -d, --data-path=<value>  Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
  -o, --output=<value>     (required) The output directory. Default will set to current working directory.
  --pretty                 Prints JSON in pretty format rather than condensed.

DESCRIPTION
  Export to <FILE>.

EXAMPLES
  keys:export --output /mypath/keys.json

  keys:export --output /mypath/keys.json --data-path ./data
----

.Example 
[%collapsible]
====
[source,bash]
----
$ lisk-core keys:export --output ~/mypath/mykeys.json
----
====

==== keys:import
Import keys from a file.

[source,bash]
----
USAGE
  $ lisk-core keys import -f <value> [-d <value>] [--pretty]

FLAGS
  -d, --data-path=<value>  Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
  -f, --file-path=<value>  (required) Path of the file to import from
  --pretty                 Prints JSON in pretty format rather than condensed.

DESCRIPTION
  Import from <FILE>.

EXAMPLES
  keys:import --file-path ./my/path/keys.json

  keys:import --file-path ./my/path/keys.json --data-path ./data
----

.Example 
[%collapsible]
====
[source,bash]
----
$ lisk-core keys:import --file-path ~/mykeys.json
----
====

=== passphrase
Commands relating to Lisk Core passphrases.

[source,bash]
----
USAGE
  $ lisk-core passphrase COMMAND

COMMANDS
  passphrase create   Returns a randomly generated 24 words mnemonic passphrase.
  passphrase decrypt  Decrypt secret passphrase using the password provided at the time of encryption.
  passphrase encrypt  Encrypt secret passphrase using password.
----

==== passphrase:create
Decrypts the secret passphrase using the password provided at the time of encryption.

[source,bash]
----
USAGE
  $ lisk-core passphrase create [-o <value>]

FLAGS
  -o, --output=<value>  The output directory. Default will set to current working directory.

DESCRIPTION
  Returns a randomly generated 24 words mnemonic passphrase.

EXAMPLES
  passphrase:create

  passphrase:create --output /mypath/passphrase.json
----

.Example 
[%collapsible]
====
[source,bash]
----
$ lisk-core passphrase create
{
  "passphrase": "lava empower laundry taxi believe cute boss stairs bicycle vivid dirt vendor accuse identify general run knock medal chief space remain flush extra bike"
}
----
====

==== passphrase:decrypt
Decrypts the secret passphrase using the password provided at the time of encryption.

[source,bash]
----
USAGE
  $ lisk-core passphrase decrypt -f <value> [-w <value>]

FLAGS
  -f, --file-path=<value>  (required) Path of the file to import from
  -w, --password=<value>   Specifies a source for your secret password. Command will prompt you for input if this option is not set.
                           	Examples:
                           	- --password=pass:password123 (should only be used where security is not important)

DESCRIPTION
  Decrypt secret passphrase using the password provided at the time of encryption.

EXAMPLES
  passphrase:decrypt --file-path ./my/path/output.json

  passphrase:decrypt --file-path ./my/path/output.json --password your-password
----

.Example 
[%collapsible]
====
[source,bash]
----
$ lisk-core passphrase:decrypt --file-path ./my/path/keys.json
? Please enter password:  [hidden]
? Please re-enter password:  [hidden]
{"passphrase":"my secret passphrase"}
----
====

==== passphrase:encrypt
Encrypts the secret passphrase using a password.

[source,bash]
----
USAGE
  $ lisk-core passphrase encrypt [-w <value>] [-p <value>] [--output-public-key] [-o <value>]

FLAGS
  -o, --output=<value>      The output directory. Default will set to current working directory.
  -p, --passphrase=<value>  Specifies a source for your secret passphrase. Command will prompt you for input if this option is not set.
                            	Examples:
                            	- --passphrase='my secret passphrase' (should only be used where security is not important)
  -w, --password=<value>    Specifies a source for your secret password. Command will prompt you for input if this option is not set.
                            	Examples:
                            	- --password=pass:password123 (should only be used where security is not important)
  --output-public-key       Includes the public key in the output. This option is provided for the convenience of node operators.

DESCRIPTION
  Encrypt secret passphrase using password.

EXAMPLES
  passphrase:encrypt

  passphrase:encrypt --passphrase your-passphrase --output /mypath/keys.json

  passphrase:encrypt --password your-password

  passphrase:encrypt --password your-password --passphrase your-passphrase --output /mypath/keys.json

  passphrase:encrypt --output-public-key --output /mypath/keys.json
----

.Example 
[%collapsible]
====
[source,bash]
----
$ lisk-core passphrase:encrypt -p 'my secret passphrase'
? Please enter password:  [hidden]
? Please re-enter password:  [hidden]
{
  "encryptedPassphrase": {
    "ciphertext": "f0abd47a3095f288f3b291a883222cd64d7748b0",
    "mac": "f88e98d461c9be73bcf8f3b37e5e8123a7f7ce351fcdf3b9c9f226f5e07d9cda",
    "kdf": "argon2id",
    "kdfparams": {
      "parallelism": 4,
      "iterations": 1,
      "memorySize": 2024,
      "salt": "a5e440ce3bc216ec8b2bc122155971c9"
    },
    "cipher": "aes-256-gcm",
    "cipherparams": {
      "iv": "272b5a4caa0b3605ae9837b0",
      "tag": "7a0601cc12ca169300aba9a9f53c652b"
    },
    "version": "1"
  }
}
----
====






























// === start

// Starts the Lisk Core node.

// [source,bash]
// ----
// USAGE
//   $ lisk-core start

// OPTIONS
//   -c, --config=config                                    File path to a custom config. Environment variable "LISK_CONFIG_FILE" can also be used.
//   -d, --data-path=data-path                              Directory path to specify where node data is stored. Environment variable "LISK_DATA_PATH" can also be used.
//   -l, --log=trace|debug|info|warn|error|fatal            File log level. Environment variable "LISK_FILE_LOG_LEVEL" can also be used.
//   -n, --network=network                                  [default: mainnet] Default network config to use. Environment variable "LISK_NETWORK" can also be used.
//   -p, --port=port                                        Open port for the peer to peer incoming connections. Environment variable "LISK_PORT" can also be used.
//   --api-ipc                                              Enable IPC communication. This will also load up plugins in child process and communicate over IPC.
//   --api-ws                                               Enable websocket communication for api-client.
//   --api-ws-host=api-ws-host                              Host to be used for api-client websocket.
//   --api-ws-port=api-ws-port                              Port to be used for api-client websocket.
//   --console-log=trace|debug|info|warn|error|fatal        Console log level. Environment variable "LISK_CONSOLE_LOG_LEVEL" can also be used.
//   --enable-forger-plugin                                 Enable Forger Plugin. Environment variable "LISK_ENABLE_FORGER_PLUGIN" can also be used.
//   --enable-http-api-plugin                               Enable HTTP API Plugin. Environment variable "LISK_ENABLE_HTTP_API_PLUGIN" can also be used.
//   --enable-monitor-plugin                                Enable Monitor Plugin. Environment variable "LISK_ENABLE_MONITOR_PLUGIN" can also be used.
//   --enable-report-misbehavior-plugin                     Enable ReportMisbehavior Plugin. Environment variable "LISK_ENABLE_REPORT_MISBEHAVIOR_PLUGIN" can also be used.
//   --http-api-plugin-host=http-api-plugin-host            Host to be used for HTTP API Plugin. Environment variable "LISK_HTTP_API_PLUGIN_HOST" can also be used.
//   --http-api-plugin-port=http-api-plugin-port            Port to be used for HTTP API Plugin. Environment variable "LISK_HTTP_API_PLUGIN_PORT" can also be used.
//   --http-api-plugin-whitelist=http-api-plugin-whitelist  List of IPs in comma separated value to allow the connection. Environment variable "LISK_HTTP_API_PLUGIN_WHITELIST" can also be used.
//   --monitor-plugin-host=monitor-plugin-host              Host to be used for Monitor Plugin. Environment variable "LISK_MONITOR_PLUGIN_HOST" can also be used.
//   --monitor-plugin-port=monitor-plugin-port              Port to be used for Monitor Plugin. Environment variable "LISK_MONITOR_PLUGIN_PORT" can also be used.
//   --monitor-plugin-whitelist=monitor-plugin-whitelist    List of IPs in comma separated value to allow the connection. Environment variable "LISK_MONITOR_PLUGIN_WHITELIST" can also be used.
//   --overwrite-config                                     Overwrite network configs if they exist already

//   --seed-peers=seed-peers                                Seed peers to initially connect to in format of comma separated "ip:port". IP can be DNS name or IPV4 format. Environment variable "LISK_SEED_PEERS" can also be
//                                                          used.

// EXAMPLES
//   start
//   start --network devnet --data-path /path/to/data-dir --log debug
//   start --network devnet --api-ws
//   start --network devnet --api-ws --api-ws-host 0.0.0.0 --api-ws-port 8888
//   start --network devnet --port 9000
//   start --network devnet --port 9002 --seed-peers 127.0.0.1:9001,127.0.0.1:9000
//   start --network testnet --overwrite-config
//   start --network testnet --config ~/my_custom_config.json
// ----

// === hash-onion

// Creates hash onions to be used by a delegate.

// [source,bash]
// ----
// USAGE
//   $ lisk-core hash-onion

// OPTIONS
//   -c, --count=count        [default: 1000000] Total number of hashes to produce
//   -d, --distance=distance  [default: 1000] Distance between each hashes
//   -o, --output=output      Output file path

// EXAMPLE
//   hash-onion --count=1000000 --distance=2000
// ----

// == Topics

// === account

// [source,bash]
// ----
// Commands relating to Lisk Core accounts.

// USAGE
//   $ lisk-core account:COMMAND

// COMMANDS
//   account:create    Return randomly-generated mnemonic passphrase with its corresponding public/private key pair and Lisk address.
//   account:get       Get account information for a given address.
//   account:show      Show account information for a given passphrase.
//   account:validate  Validate base32 address.
// ----

// === block

// [source,bash]
// ----
// Commands relating to Lisk Core blocks.

// USAGE
//   $ lisk-core block:COMMAND

// COMMANDS
//   block:get  Get block information for a given id or height.
// ----

// === blockchain

// [source,bash]
// ----
// Commands relating to Lisk Core blockchain data.

// USAGE
//   $ lisk-core blockchain:COMMAND

// COMMANDS
//   blockchain:download  Download snapshot from <URL>.
//   blockchain:export    Export to <FILE>.
//   blockchain:hash      Generate SHA256 hash from <PATH>.
//   blockchain:import    Import from <FILE>.
//   blockchain:reset     Reset the blockchain data.
// ----

// === config

// [source,bash]
// ----
// Commands relating to Lisk Core node configuration.

// USAGE
//   $ lisk-core config:COMMAND

// COMMANDS
//   config:show  Show application config.
// ----

// === forger-info

// [source,bash]
// ----
// Commands relating to Lisk Core forger-info data.

// USAGE
//   $ lisk-core forger-info:COMMAND

// COMMANDS
//   forger-info:export  Export to <FILE>.
//   forger-info:import  Import from <FILE>.
// ----

// === forging

// [source,bash]
// ----
// Commands relating to Lisk Core forging.

// USAGE
//   $ lisk-core forging:COMMAND

// COMMANDS
//   forging:disable  Disable forging for given delegate address.
//   forging:enable   Enable forging for given delegate address.
//   forging:config   Generate delegate forging config for given passphrase and password.
//   forging:status   Get forging information for the locally running node.
// ----

// ==== forging:config

// [source,bash]
// ----
// lisk-core forging:config --help
// Generate delegate forging config for given passphrase and password.

// USAGE
//   $ lisk-core forging:config

// OPTIONS
//   -c, --count=count            [default: 1000000] Total number of hashes to produce
//   -d, --distance=distance      [default: 1000] Distance between each hashes
//   -o, --output=output          Output file path

//   -p, --passphrase=passphrase  Specifies a source for your secret passphrase. Command will prompt you for input if this option is not set.
//                                	Examples:
//                                	- --passphrase='my secret passphrase' (should only be used where security is not important)

//   -w, --password=password      Specifies a source for your secret password. Command will prompt you for input if this option is not set.
//                                	Examples:
//                                	- --password=pass:password123 (should only be used where security is not important)

//   --pretty                     Prints JSON in pretty format rather than condensed.

// EXAMPLES
//   forging:config
//   forging:config --password your_password
//   forging:config --passphrase your_passphrase --password your_password --pretty
//   forging:config --count=1000000 --distance=2000 --output /tmp/forging_config.json
// ----

// === node

// [source,bash]
// ----
// Commands relating to Lisk Core node.

// USAGE
//   $ lisk-core node:COMMAND

// COMMANDS
//   node:info  Get node information from a running application.
// ----

// === passphrase

// [source,bash]
// ----
// Commands relating to Lisk Core passphrases.

// USAGE
//   $ lisk-core passphrase:COMMAND

// COMMANDS
//   passphrase:decrypt  Decrypt secret passphrase using the password provided at the time of encryption.
//   passphrase:encrypt  Encrypt secret passphrase using password.
// ----

// === sdk

// [source,bash]
// ----
// Commands relating to Lisk SDK development.

// USAGE
//   $ lisk-core sdk:COMMAND

// COMMANDS
//   sdk:link  Symlink specific SDK folder during development.
// ----

// === transaction

// [source,bash]
// ----
// Commands relating to Lisk Core transactions.

// USAGE
//   $ lisk-core transaction:COMMAND

// COMMANDS
//   transaction:create  Create transaction which can be broadcasted to the network. Note: fee and amount should be in Beddows!!
//   transaction:get     Get transaction from local node by ID.
//   transaction:send    Send transaction to the local node.
//   transaction:sign    Sign encoded transaction.
// ----

// [[structure]]
// == Config file structure

// The configuration for Lisk Core is stored in `~/.lisk/lisk-core/config` footnote:snap_footnote[Snap versions of Lisk Core store everything in `~/snap/lisk-core/current/.lisk/lisk-core` instead of `~/.lisk/lisk-core`].
// Each network uses a separate configuration.

// .~/.lisk/lisk-core/config/devnet/config.json footnote:snap_footnote[]
// [source,json]
// ----
// {
//     "rpc": {
//       "enable": false,
//       "mode": "ipc",
//       "port": 8080,
//     },
//     "networkVersion": "2.0",
//     "label": "devnet",
//     "genesisConfig": {
//         "blockTime": 10,
//         "communityIdentifier": "Lisk",
//         "maxPayloadLength": 15360,
//         "bftThreshold": 68,
//         "minFeePerByte": 1000,
//         "baseFees": [
//             {
//                 "moduleID": 5,
//                 "assetID": 0,
//                 "baseFee": "1000000000"
//             }
//         ],
//         "rewards": {
//             "milestones": ["500000000", "400000000", "300000000", "200000000", "100000000"],
//             "offset": 2160,
//             "distance": 3000000
//         },
//         "minRemainingBalance": "5000000",
//         "activeDelegates": 101,
//         "standbyDelegates": 2,
//         "delegateListRoundOffset": 2
//     },
//     "logger": {
//         "fileLogLevel": "debug",
//         "consoleLogLevel": "info"
//     },
//     "network": {
//         "port": 5000,
//         "seedPeers": [
//             {
//                 "ip": "127.0.0.1",
//                 "port": 5000
//             }
//         ]
//     },
//     "forging": {
//         "force": true,
//         "waitThreshold": 2,
//         "delegates": [],
//         "defaultPassword": "elephant tree paris dragon chair galaxy"
//     },
//     "plugins": {}
// }
// ----