= Update Docker setup
Christopher Braithwaite <christopher.braithwaite@lightcurve.io>
:description: How to update up a Lisk Core node with Docker.
:toc:
// Settings
// External URLs
:url_core_releases: https://github.com/LiskHQ/lisk-core/releases
:url_podman: https://github.com/containers/podman/
:url_docker_install: https://docs.docker.com/engine/installation/#desktop
:url_docker_install_linux: https://docs.docker.com/engine/installation/#server
:url_docker_install_mac: https://docs.docker.com/docker-for-mac/install/
:url_docker_install_windows: https://docs.docker.com/docker-for-windows/install/
:url_docker_linux_post_install: https://docs.docker.com/install/linux/linux-postinstall
:url_xcode: https://developer.apple.com/xcode/features/
:url_devnet_passphrase: https://github.com/LiskHQ/lisk-core/blob/development/config/devnet/passphrase.json
// Project URLs
:url_config: management/configuration.adoc
:url_upgrade_source: update/source.adoc
:url_run_logging: lisk-core::run-blockchain/logging.adoc
:url_run_logging: ROOT::run-blockchain/logging.adoc
:fn: footnote:hdd[These recommendations are derived from the log level settings, in the event that the user needs to increase storage to prevent limited memory access and potential memory-related problems with a node. Furthermore, as more transactions are processed and added to the blockchain, the size of the blockchain increases over time and this directly affects the HDD storage requirements for a blockchain node. Hence, adhering to the above listed requirements is highly recommended.]

This document describes how to run Lisk Core as a Docker image-based container.
Lisk Core version 4 does not have any external dependencies and hence does not require using `docker-compose`.


== Upgrade Lisk Core

To upgrade the Docker container to a desired version, please follow one of the two options below.
To find all the tagged versions for Lisk Core, please check the {url_tags}[available tags] on GitHub.

[tabs]
====
Option A - Download pre-built images from DockerHub::
+
--
. Stop Lisk Core
+
----
make stop
----
NOTE: In case the database needs to be flushed please execute the `make down` command instead. Please check the {url_rel_notes}[release notes] for the relevant version to see if the existing databases need to be flushed.

. Manually download the image from `DockerHub`.
+

[source,sh]
----
docker image pull lisk-core
----
NOTE: To download a specific version of Lisk Core, please include the tag after `lisk-core` in the above command. For example, `lisk-core:4.0.0`

. Start Lisk Core in the containers.
+
----
make start ARGS="-n mainnet --api-ws"
----
NOTE: Please customize `ARGS` as per your requirements.
--
Option B - Build images locally ::
+
--
Build the images locally using the following steps.
Navigate inside the lisk-core root folder, and execute the following commands.

. Stop Lisk Core
+
----
make stop
----
NOTE: In case the database needs to be flushed please execute the `make down` command instead. Please check the {url_rel_notes}[release notes] for the relevant version to see if the existing databases need to be flushed.

. Checkout the version with *`git checkout <tag>`*
+
----
git checkout v4.0.0
----

. Build the required updated Docker image
+
----
make build-image
----

. Start Lisk Core in the container
+
----
make start ARGS="-n mainnet --api-ws"
----
NOTE: Please customize `ARGS` as per your requirements.
--

====

// Check this : To verify the microservice logs, please refer to the <<Logging>> section.

